#!/bin/bash

base_dir="FLAD-PCAPS"
output_base_dir="PCAP-CHUNKS"

pcap_files=(
    "05-NTP/ntp-chunk.pcap"
    "05-NTP/ntp-chunk1.pcap"
    "05-NTP/ntp-chunk2.pcap"
    "05-NTP/ntp-chunk3.pcap"
    "05-NTP/ntp-chunk4.pcap"
    "05-NTP/ntp-chunk5.pcap"
    "05-NTP/ntp-chunk6.pcap"
    "05-NTP/ntp-chunk7.pcap"
    "05-NTP/ntp-chunk8.pcap"
    "05-NTP/ntp-chunk9.pcap"
    "06-SNMP/snmp-chunk.pcap"
    "06-SNMP/snmp-chunk1.pcap"
    "06-SNMP/snmp-chunk2.pcap"
    "06-SNMP/snmp-chunk3.pcap"
    "06-SNMP/snmp-chunk4.pcap"
    "06-SNMP/snmp-chunk5.pcap"
    "06-SNMP/snmp-chunk6.pcap"
    "06-SNMP/snmp-chunk7.pcap"
    "06-SNMP/snmp-chunk8.pcap"
    "06-SNMP/snmp-chunk9.pcap"
    "06-SNMP/snmp-chunk10.pcap"
    "06-SNMP/snmp-chunk11.pcap"
    "06-SNMP/snmp-chunk12.pcap"
    "06-SNMP/snmp-chunk13.pcap"
    "06-SNMP/snmp-chunk14.pcap"
    "07-SSDP/ssdp-chunk.pcap"
    "07-SSDP/ssdp-chunk1.pcap"
    "07-SSDP/ssdp-chunk2.pcap"
    "07-SSDP/ssdp-chunk3.pcap"
    "07-SSDP/ssdp-chunk4.pcap"
    "07-SSDP/ssdp-chunk5.pcap"
    "07-SSDP/ssdp-chunk6.pcap"
    "07-SSDP/ssdp-chunk7.pcap"
    "07-SSDP/ssdp-chunk8.pcap"
    "07-SSDP/ssdp-chunk9.pcap"
    "07-SSDP/ssdp-chunk10.pcap"
    "07-SSDP/ssdp-chunk11.pcap"
    "07-SSDP/ssdp-chunk12.pcap"
    "07-SSDP/ssdp-chunk13.pcap"
    "08-Syn/syn-chunk.pcap"
    "08-Syn/syn-chunk1.pcap"
    "08-Syn/syn-chunk2.pcap"
    "08-Syn/syn-chunk3.pcap"
    "08-Syn/syn-chunk4.pcap"
    "08-Syn/syn-chunk5.pcap"
    "08-Syn/syn-chunk6.pcap"
    "09-TFTP/tftp-chunk.pcap"
    "09-TFTP/tftp-chunk1.pcap"
    "09-TFTP/tftp-chunk2.pcap"
    "09-TFTP/tftp-chunk3.pcap"
    "09-TFTP/tftp-chunk4.pcap"
    "09-TFTP/tftp-chunk5.pcap"
    "09-TFTP/tftp-chunk6.pcap"
    "09-TFTP/tftp-chunk7.pcap"
    "09-TFTP/tftp-chunk8.pcap"
    "09-TFTP/tftp-chunk9.pcap"
    "10-UDP/udp-chunk.pcap"
    "10-UDP/udp-chunk1.pcap"
    "10-UDP/udp-chunk2.pcap"
    "10-UDP/udp-chunk3.pcap"
    "10-UDP/udp-chunk4.pcap"
    "10-UDP/udp-chunk5.pcap"
    "10-UDP/udp-chunk6.pcap"
    "10-UDP/udp-chunk7.pcap"
    "10-UDP/udp-chunk8.pcap"
    "10-UDP/udp-chunk9.pcap"
    "10-UDP/udp-chunk10.pcap"
    "10-UDP/udp-chunk11.pcap"
    "10-UDP/udp-chunk12.pcap"
    "10-UDP/udp-chunk13.pcap"
    "10-UDP/udp-chunk14.pcap"
    "10-UDP/udp-chunk15.pcap"
    "11-NetBIOS/netbios-chunk.pcap"
    "11-NetBIOS/netbios-chunk1.pcap"
    "11-NetBIOS/netbios-chunk2.pcap"
    "11-NetBIOS/netbios-chunk3.pcap"
    "11-NetBIOS/netbios-chunk4.pcap"
    "11-NetBIOS/netbios-chunk5.pcap"
    "11-NetBIOS/netbios-chunk6.pcap"
    "11-NetBIOS/netbios-chunk7.pcap"
    "11-NetBIOS/netbios-chunk8.pcap"
    "11-NetBIOS/netbios-chunk9.pcap"
    "11-NetBIOS/netbios-chunk10.pcap"
    "11-NetBIOS/netbios-chunk11.pcap"
    "11-NetBIOS/netbios-chunk12.pcap"
    "11-NetBIOS/netbios-chunk13.pcap"
    "11-NetBIOS/netbios-chunk14.pcap"
    "12-MSSQL/mssql-chunk0.pcap"
    "12-MSSQL/mssql-chunk1.pcap"
    "12-MSSQL/mssql-chunk2.pcap"
    "12-MSSQL/mssql-chunk3.pcap"
    "12-MSSQL/mssql-chunk4.pcap"
    "12-MSSQL/mssql-chunk5.pcap"
    "12-MSSQL/mssql-chunk6.pcap"
    "12-MSSQL/mssql-chunk7.pcap"
)

for rel_path in "${pcap_files[@]}"; do
    input_path="${base_dir}/${rel_path}"

    # Extract filename and directory from relative path
    filename=$(basename "$rel_path" .pcap)
    subdir=$(dirname "$rel_path")

    # Set output directory structured by subdirectories
    output_dir="${output_base_dir}/${subdir}/${filename}"
    mkdir -p "$output_dir"

    echo "➤ Splitting $input_path into $output_dir"

    # Split file into 75MB chunks, outputs files like filename_chunk.pcap00, filename_chunk.pcap01, etc.
    tcpdump -r "$input_path" -C 75 -w "${output_dir}/${filename}_chunk.pcap"

    # Correctly rename files to place serial number before .pcap
    for f in "${output_dir}/${filename}_chunk.pcap"*; do
        [ -e "$f" ] || continue
        suffix="${f##*.pcap}" # get the numeric suffix
        mv "$f" "${output_dir}/${filename}_chunk${suffix}.pcap"
    done
done
